language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 2.7
      env: TOXENV=py27
before_install:
  - pip install numpy
install:
  - pip install tox
script:
  - tox